name: Deployment to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/deploy-dockerize-django-ec2
          git checkout staging
          git pull origin staging
          sudo docker-compose -f "./build-process/docker-compose-django-backend.yml" up -d --build
          sudo docker exec backend-django-production python manage.py migrate
          sudo service nginx restart
          sleep 10  # Add a sleep for 10 seconds after restarting nginx
          sudo docker image prune -a -f
          sudo docker builder prune -f

